name: calculator_lexemes
description: Приложения для парсинга математических выражений на основе лексем на языке Dart.
  Переработанная версия java приложения https://github.com/Arhiser/java_tutorials/blob/master/src/ru/arhiser/parser/Main.java
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
